name: Build iOS

on:
  push:
    branches:
      - master
      - with-admob
  pull_request:
    branches:
      - master
      - with-admob

jobs:
  build:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3 # Use v3, it's recommended
      with:
        lfs: true # This option is important for correctly fetching LFS files

    - name: Download Godot 4.3
      run: |
        wget https://github.com/godotengine/godot/releases/download/4.3-stable/Godot_v4.3-stable_macos.universal.zip
        unzip Godot_v4.3-stable_macos.universal.zip -d godot
        sudo mv godot/Godot.app /Applications/Godot.app
        sudo ln -s /Applications/Godot.app/Contents/MacOS/Godot /usr/local/bin/godot

    - name: Download Godot 4.3 Export Templates
      run: |
        mkdir -p ~/Library/Application\ Support/Godot/export_templates/4.3.stable
        wget https://github.com/godotengine/godot/releases/download/4.3-stable/Godot_v4.3-stable_export_templates.tpz
        tar -xzf Godot_v4.3-stable_export_templates.tpz -C ~/Library/Application\ Support/Godot/export_templates/4.3.stable --strip-components=1

    - name: Download MoltenVK
      run: |
        wget https://github.com/KhronosGroup/MoltenVK/releases/download/v1.2.11-artifacts/MoltenVK-ios.tar
        tar -xvf MoltenVK-ios.tar
        mv MoltenVK/MoltenVK/static/MoltenVK.xcframework ./

    - name: Create build directory
      run: mkdir -p build

    - name: Export iOS project
      run: godot --headless --export-release "iOS" build/empty-test.xcodeproj
      env:
        DISPLAY: :99.0
        
    - name: Run Admob scripts
      run: |
        cd ./build/empty-test/ios/plugins/poing-godot-admob/scripts
        chmod +x update_and_install.sh
        ./update_and_install.sh
        cd ../../../../../../
        
    - name: Set iOS Deployment Target
      run: sed -i '' 's/IPHONEOS_DEPLOYMENT_TARGET = 10.0;/IPHONEOS_DEPLOYMENT_TARGET = 12.0;/' build/empty-test.xcodeproj/project.pbxproj

    - name: Build iOS project
      run: |
        xcodebuild -project build/empty-test.xcodeproj \
        -scheme empty-test \
        -configuration Development \
        -archivePath build/empty-test.xcarchive archive \
        CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO CODE_SIGNING_ALLOWED=NO

    - name: Export IPA
      run: | 
        cd build
        cd empty-test.xcarchive
        cd Products
        cd Applications
        mkdir Payload
        mv empty-test.app Payload/
        zip -r App.ipa Payload/
        mv App.ipa ../../../

    - name: Upload IPA to GitHub Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: Ipa
        path: build/App.ipa

